node-preset: &node # Used internally to share configuration, ignored by travis.
  language: node_js
  node_js:
    - "8"
  cache:
    yarn: true
    directories:
      - node_modules
branches:
  only:
  - master
  # tags
  - /^\d+\.\d+\.\d+(\-beta.\d+)?$/
stages:
  - test
  - build
jobs:
  include:
    - name: Unit tests
      stage: test
      <<: *node
      script:
        - yarn lint
        - yarn test
    - name: Web build
      stage: build
      <<: *node
      script:
        - yarn build
      before_deploy:
        - yarn secrets:decrypt
        - eval "$(ssh-agent -s)"
        - chmod 600 ./scripts/decrypted/id_rsa
        - ssh-add ./scripts/decrypted/id_rsa
      deploy:
        - provider: script
          repo: cozy/cozy-banks
          skip-cleanup: true
          script:
            - yarn cozyPublish
            - yarn uploadStaticFiles
          on:
            branch: master
        - provider: script
          repo: cozy/cozy-banks
          skip-cleanup: true
          script:
            - yarn cozyPublish
            - yarn uploadStaticFiles
          on:
            tags: true
    - name: Android build
      stage: build
      os: linux
      language: android
      android:
        components:
          - build-tools-26.0.2
      before_script:
        - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
        - sudo apt-get install nodejs
        - sudo apt-get install build-essential
        - yarn
        - yarn mobile:icon
        - yarn secrets:decrypt
        - ln -s ../../../scripts/decrypted/keys ./src/targets/mobile/keys
        - gem update --system
        - rvm install 2.6.0
        - gem install bundler
      script:
        - yarn android:build
env:
  global:
    - MATTERMOST_CHANNEL=Gangsters-release
    # kosssi GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=<your_GITHUB_TOKEN> -r cozy/cozy-banks
    - secure: "e9//FM2xEZScLWqLcm25HHvoZTROExVW255fvOlGsQjGB+7jcYFOwGpbvq+58syGowrbfles7rexaGe9AwSGtnHEHdEH0gPwCOYo5vEzdcb8L0w6wFti503Idzv8qC6bocLSGGymCozQTrFbtYZHk8gKVT6R71jR49/Vj0YVpczAHCu9JFpOmmJTwsHULlAOCDaQlRkVXqzVdIT1G+mKyexJo4kqYue82+kLIk5tVjV7TXWupg9x32WqbVz/EV4DZvGmGndvvEDIVwxeGcE1RYyr17QeKwNWUsDHIWXGClKitr6krR5zcDo57/nAbdWwUUzvItk1Osw1Sa0tuwInh5KCw+frDMmA9209IeDtWSJzdbGkfwtQVOAORJqaUoqJkrPwhFQIg5jTYcAKR6Xy0AYt2sm1Pc7AeaWG9Fu0z3lW9hGNDwOLKfuIuKCHK9FgE9YY75S1nH8AYUSZwCL2all8u4LH9tFtU8AzGv5ZEKwLCA/KyCUtxb11t0W6KofZIt6ripTfu5P3dhN9dEpJ8pYZ85BViBM3sl3+kyanEaxIo4Z8DVgy5ilPOgpZS/I3EiimI62CFlXT8lrao6df4coLjjHbdhWpZNFZ697heb+K2Ncd9kgjwaul1U2sJBrWjnZdcQ2KERq3q9+4TRj9EM6J006DxDO7h+d7Pa+BXz4="
    # MATTERMOST_HOOK_URL
    - secure: "i40PC82nF00ixRI/uArDG48tY99DYg4/gu9EpRXK8BeV/Uh6WVT5MpBbd8JEyf3fLZFXVwdbBPrsEUw4aX2fdfbueRqaigLbYz3rejNGL2YjE28ZBmFQeoPviHz8cOJepcjUrgggkiyD14qvAyoPJCEo/pPx1ZCsZ2UCQHu5SIw9Mtf2kvspgNyhpl3ktm/L4wh+8huRE7/Zn6SKStps5F7MWrUp5zZ6ZovHLl8ti71p2KhCCIJL30PGoh58O3aH3t7LY2bUetQS6p0a4OxWUF3AE5wakzffvqvrHqMI4ulkREYq/J6b7ITkHhxL9V1ndCvQyw4aC5OUR4Dl3GznSfkvby9NNyNcK4lxeOgjejvSrmPV5gEmCPjnpyijkMidy/5OMOCeQIXtWw7Cly+Mnj1kWz6bFnLncs1SBqdxUSUa+jTPZ8tklAiz4hdkGgtPxpovyo4iQdNQVmL8y2v7XWuXvpdGTEuZgGIubH3+HDOwa3dawC6BglnY1W0sp3hvYUaEKyPolP/mCV9HRSZ0Aa1zjjNW2brbUaEJ6w1UMT7XwQQQtb35K+zQSBCn9jfNyuDdotsh+mJEILk0tsB3aYcVnvLUKChpTt23bV5sMxga0F/Mmmwb8y8DWE8u7ADWDjzdDnoaqInSj9RAYVgFguhWpZhVs6yuGd16Bi7kvoU="
    # RUNDECK_TOKEN
    - secure: "rwvCE17fZRfx9wi692wU+ox/oKx8dSeit5WbPxq6c6Jj39IfaKaeXBgDVaG1HsvY6RhhXKJ6t1hrUGNzLOJdPDvfkQKEPDlKgbJoFstCke2aj3guOLx/aSzdoB2fUTWjaIKtrVZFtC60YK9dr1g9UzrFru0Fe6JP/XN2fIqqR3wwzWln1bYVINwWPj+HQNZO9YIejKei7ooSO+FSf/C9nqMkELNv89x8yAZASGejfhayPvRlbT2CF8Ym0GkqEBRNRqHfURGE4m9mUEPIv7vQ0uPnH9dwwQrZf6KXCHIoG+O5sH54V4M28FBMTHYF/3GflcJFm3qNnffoOcUl5/K3LQWKbeShw7W+BjuPbjXSLZICnENWeXHmvjYjUN4niUxwWewM+a5k+5LgcEd/ZLrWui6KFAjl1SGqu97hBRPCDelF/ssTfh0UwM4brSQ3Dgi3bLex49VDPmA63/vtH5HRQ+7EM+FcaEnFsaA5cUaGOQAExIySSzimyjSF5seOJcrH3QmmkTt8qsWrYMCqes6bMmx2gOgQQ2vAvxrtJyunhriiEKWTnLOGwdB7AyS5A6QF1K3FodLAqDYwQgkSYSS4isv2RNT5Bilk9hJ1IVs82ZgepOpwkhygae2/2n4ZUv9ynol0f083BG+vNVb6b79o4ZHrsfTQatu9Mlrorug6a0Y="
    # REGISTRY_TOKEN
    - secure: "q0e3QfSHzD7u03W/uRmZ/1CgwLrdO2GuWD/9fPXTYXI9vnu0Z4xPLGHv0zzshgdH4qNyIJ+74KCfk2ev6FvG+8Z15qNkdbwLjQxn3TDK48dfjC8C1SWfa55r2hjMo/qYXgLhBpdaVeGLyvpvmmKB+MsqKVugr1V41iBLfXNustJ2smvCkjKiRWH7Jl6jeMWQ+paL5WccK6DF5GqoPc3RCdSoXNhhPOelmo2NI/XF1MFRNToc5Fl5yIquivJdb7nA1UTB+DKZOX0I4+6sJpecuseNFdnm938QuMRaRgiKChqH+lesMSDy9+m5qp/ftByXdZIUxqxeROxNF5sVG1IxC6CNnpqsltNAAnGOHT9laQaWrfjQHUMb7pC5fjR1JN5Y3N5ZspLlnDKeEpZc3muqbyRcJDDRl2lAxgtt1MDyOD3u2IuCwa8xKysZzDHBjIQDChr01mWmTb3tOt7iwSc7HekOnfa2VHvlQfiWD/JSKLRLGoX3GC/RljuIC7SxufUojV9vn2heROPk9b95wnHGce3rmHPuECfxuLAU2PN84S9j+j371AJ4/UsQhGV9Gyl3Bgua/6X82pooN4/Q/0RURJrQ8DUPkQ1wbDHCOeaDB97ZvcQi3bGUh+AiElSaHS+V7c6kne7QRmCPcn9NnlKmz7YPd141922WMIUunoc7guI="
    # ENCRYPTED_KEY
    - secure: "MkxSVyjNwHPfuCA4kdrTeBRbmDV2j4wcvD7416ykZYSh2ixHnSFxDyi5cabCW2Rzz4+JDh2GUBL/mIJr5PvqKHRRV5Ehtu/fN8b53PjmcuREBzK3JMsuWtT0PMqfM633l0YAFhqLkoyDsRzpKofbw9LMQumapSOcHnODONoTgPfr0RixP7yaGkARB4ythdiCfbSK6BceS1q+XXfi2/aZh915l9Edjhs5T/3tJt8ufr8JuBV3dILk/3G7tgku6YI7SDNum6u6FVny+o23e+vzfkgDPDXVPECplAWaAt8VzasDafyVR1C4jFm+QY0D5QOnhcUmFZ04P1ng3690AI67QVgk+UUO3kpiFlKO4LhkKNf6z+gnGmYI87yz0VywcNrMwwiZC7f/yJee7mtF2YGndiO8NCISCORe3fi/gh19SOB4je8+g/CVWYU6tz7D5Ci5UKBMglnPP1o/TsO2J7VEbs9HqwfsBxghLo988KDeqtIaXCLY3Buro29jGgbYLcT9h7qG/Q3F1b4Z5Dga4FzPUQ4D11yXbv1pip1UNTwTWzyyY5YemIr0M7c4Z6JrndrrNact/iIUOW3rBoXVuWnltHfmVyXIfognBDGiB4YUHDdhSZd4etIQxID9cbEfdsL2xycrpH2bdqX9ePYK+DahBmx+qUESVpcMvW4cTYJygIY="
    # ENCRYPTED_IV
    - secure: "iz1NO2t2ZSEpc7CMz2CtMNXyFa4FTLRZu9wPlnx1IwXHTworqJ8ENSAv4kDHOFYWXubHb52c2c3dMMLLZtHxRpTtnHRvEDCHzLdc6RP5wnoOLogtfSzD140g94+iPEaXfg6hJ/Wv1nE+iBTtfDTpRMy8e/i+InU4af3FcwqMJW1oroslgd9ubZV+KUuv4nHZNOxTW67lLUQ2iRI3b7Ewjo/zkhMgCGLz4lnSO6KnspgKQ6VUA+UeV+Xx28Y5mDpH2ouhfajji6xUHptoB9AG2WZf6GfpOOMB5gxSnGNf6BiVal/TyG0unMiUy6dij+6XYnSpmG6EWna7nR35M4PD7pIwiOzcvwVwvZ4j5GnXIoIOA12Wd9vP8iPmji509slgsut00qFbgU4Uxii8ElGuDdChGzdVXuSYUBLtX7ldMcYKLMckyn/wBnWndQrDNv5jDROms+8YxNIFbm4kRM3ynt1xMFtm2v43Cj/VQ+ZwFV0cr3Y6y4QoThBrnuFXHIXJfe8HsuYZaGPpa9Jf1SDRNut7ClmvGm5+Yf+gkG1Csm82perZ1SQBtyBdtEPF71zQ1ktWYduQrG6jLb4On5zcGZ+CmPdjOopNatq6AatpFYpuZkVyhTbyn626fRIOCgbyDkgSS6yBweUB5eq8EW7Fdu8jqB0fR5+WKISe7m6dpTg="
